params:
  training_experiment: baselines.train_hmm
  validation_metric: best_ts_f1_score
  evaluation_metrics:
    - best_ts_f1_score
    - ts_auprc
    - best_ts_f1_score_classic
    - ts_auprc_unweighted
    - best_f1_score
    - auprc
training_param_updates:
  training:
    epochs: 1
detector_param_grid:
  detector_params:
    n_components:
      - 2
      - 4
      - 8
      - 16
    covariance_type:
      - diag
      - full
    n_iter:
      - 50
      - 100
