# @package _global_
dataset:
  name: SWaTDataset
  ds_args:
    training: true
  pipeline:
    prediction:
      class: timesead.models.prediction.LSTMS2STargetTransform
      args:
        window_size: 50
        replace_labels: true
  test_pipeline:
    prediction:
      class: timesead.models.prediction.LSTMS2STargetTransform
      args:
        window_size: 50
        replace_labels: false
  use_dataset_pipeline: true
  split: [0.75, 0.25]
  split_axis: time

training:
  optimizer:
    class: torch.optim.Adam
    args: {}
  batch_size: 128
  batch_dim: 1
  num_workers: 0
  drop_last: false
  scheduler:
    class: torch.optim.lr_scheduler.MultiStepLR
    args:
      milestones: [20]
      gamma: 0.1
  epochs: 70
  device: cpu
  loss: torch.nn.MSELoss
  trainer: timesead.optim.trainer.Trainer
  trainer_hooks:
    - event: post_validation
      hook: timesead.optim.trainer.EarlyStoppingHook
  checkpoint_interval: 15
  deterministic: false
  seed: 0

model:
  lstm_hidden_dims: [30, 20]
  linear_hidden_layers: []
  linear_activation: torch.nn.ELU
  dropout: 0.0

experiment:
  name: recon.prediction.train_lstm_prediction_filonov
  family: prediction
  entrypoint: experiments_hydra.prediction.train_lstm_prediction_filonov
  mlflow_experiment_name: TimeSeAD-Hydra
  tracking_uri: null
  train_detector: true
  tags:
    pilot: "true"

sweep:
  selection_metric: best_ts_f1_score_classic
  validation_metric: best_ts_f1_score_classic
  evaluation_metrics:
    - best_ts_f1_score_classic
    - best_f1_score
    - auprc
  mode: max
  training_param_updates:
    training:
      epochs: 1
  training_param_grid:
    model:
      lstm_hidden_dims:
        - [30, 20]
      linear_hidden_layers:
        - []
        - [40]
      dropout:
        - 0.0
    dataset:
      pipeline:
        prediction:
          args:
            window_size:
              - 10
              - 50
              - 100
